spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wkz960327
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&usesSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
